function [] = hinfplotting(ltf, omega_range)
% HINFPLOTTING This function automates the generation of charts created via
% the hinfloop function so they are consistent and repeatable.

% define some standard colors in one place so we can reapply as needed
Ly_color = 'k-.';
Ty_color = 'g';
Sy_color = 'r';
Y_color = 'b';

%% plotting
%set(gca, 'Color','k', 'XColor','w', 'YColor','w');set(gcf, 'Color','k')
opts = sigmaoptions;
opts.Ylim = [-80, 60];
legend_location = 'south';

subplot(2,2,3)
sigma( ...
    ltf.Ly, Ly_color, ...
    ltf.Gp, '', ...
    ltf.Gc,'', ...
    omega_range,...
    opts...
    )
legend('Ly', 'Gp', 'Gc','Location', legend_location)
grid
title('Open Loop Characteristics')

subplot(2,2,1)
sigma( ...
    ltf.Ly, Ly_color, ...
    ltf.Sy, Sy_color, ...
    ltf.Wp, [Sy_color '--'], ...
    ltf.Ty, Ty_color, ...
    ltf.Wd, [Ty_color '--'],...
    ltf.Y, Y_color, ...
    ltf.Wu, [Y_color '--'], ...
    omega_range,...
    opts...
    )
legend( 'Ly', 'Sy', 'Wp','Ty', 'Wd', 'Youla', 'Wu','Location', legend_location)
grid
title('Output Sensitivity Characteristics')

subplot(2,2,2)
sigma( ...
    ltf.Lu, Ly_color, ...
    ltf.Su, Sy_color, ...
    ltf.Tu, Ty_color, ...
    omega_range,...
    opts...
    )
hold on
legend( 'Lu', 'Su','Tu', 'Location', legend_location)
grid
title('Input Sensitivity Characteristics')

subplot(2,2,4)
step(ltf.Ty, 'b', ltf.Ty.NominalValue, 'r');
% sigma( ...
%     ltf.Y, Y_color, ...
%     ltf.Wu, [Y_color '--'], ...
%     omega_range,...
%     opts...
%     )
legend('Uncertainty', 'No Uncertainty', 'Location', legend_location)
grid
title('Output Step Response Characteristics')


% figure(2)
% step(ltf.To)
% title('closed loop step response')
% grid
% 
% figure(3)
% step(Y)
% title('actuator activity under step response')
% grid
% set(gca, 'Color','k', 'XColor','w', 'YColor','w');set(gcf, 'Color','k')
% %% plotting
% figure(11)
% sigma( ...
%     ltf.To, 'c', ...
%     ltf.So, 'r', ...
%     ltf.Si, 'y-.', ...
%     Y, 'm--' ...
%     )
% legend( 'Ty', 'Sy', 'Su', 'Y', 'Location', 'best')
% grid on
% set(gca, 'Color','k', 'XColor','w', 'YColor','w');set(gcf, 'Color','k')
% 
% figure(22)
% sigma( ...
%     G_c, 'w', ...
%     G, 'g', ...
%     ltf.Lo, 'c-.', ...
%     Y, 'm--' ...
%     )
% legend( 'Gc', 'Gp', 'Ly', 'Y', 'Location', 'best')
% grid on
% set(gca, 'Color','k', 'XColor','w', 'YColor','w');set(gcf, 'Color','k')
% 
% 
% 
% end
% end
end